### ISSUE TITLE
Block Production KPI 

### ISSUE THREAD

**Issue by blrhc** [Joystream/joystream-landing#195]
KPI parameter values
Create validator benchmark

**Comment by bwhm** [comment]
WIP

## Status

I've looked at the timestamps of blocks between from block 3600 to 393000, every 600 blocks, for Rome.

Theoretically, with a 6s block time, this should have taken 2,336,400s, but:
- It has has taken 52,506 more than that.
- 1 in ~44.5 blocks are lost due to due validators going offline, or latency.
- We've had an average of 19.4 validators in this interval
